name: Build Lib

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install tools needed for building
      run: sudo apt-get update && sudo apt-get install -y cmake g++ build-essential

    - name: Create build folder
      run: mkdir build

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build Lib
      run: cmake --build build
